- hosts: dotnet
  sudo: True
  user: vagrant
  tasks:
  - name: "Make sure wget is installed"
    yum: name=wget state=latest
  - name: "Create dotnet dir"
    file: path=/home/vagrant/dotnet state=directory
  - name: "Get the .NET bits"
    unarchive: src=https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-dev-rhel-x64.latest.tar.gz dest=/home/vagrant/dotnet copy=no
  - name: "Install dependencies"
    yum: name=libicu,libuuid,libcurl,openssl,libunwind state=latest
  - name: "Set environment variables for dotnet binaries"
    shell: echo 'export DOTNET_HOME=/home/vagrant/dotnet' >> /home/vagrant/.bash_profile
  - shell: echo 'export PATH=$PATH:$DOTNET_HOME' >> /home/vagrant/.bash_profile
